vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        prestation:
            uri_prefix: /assets/images/prestations
            upload_destination: '%kernel.project_dir%/public/assets/images/prestations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

            
        
        rendezvous:
            uri_prefix: /assets/images/rendezvous
            upload_destination: '%kernel.project_dir%/public/assets/images/rendezvous'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        category_prestation:
            uri_prefix: /assets/images/categoryprestations
            upload_destination: '%kernel.project_dir%/public/assets/images/categoryprestations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        formation:
            uri_prefix: /assets/images/formations
            upload_destination: '%kernel.project_dir%/public/assets/images/formations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        home_images:
            uri_prefix: /assets/images/home
            upload_destination: '%kernel.project_dir%/public/assets/images/home'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        formation_instructor:
            uri_prefix: /assets/images/formations/instructors
            upload_destination: '%kernel.project_dir%/public/assets/images/formations/instructors'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        formation_resource:
            uri_prefix: /assets/files/formations
            upload_destination: '%kernel.project_dir%/public/assets/files/formations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
