vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        prestation:
            uri_prefix: /assets/images/prestations
            upload_destination: '%kernel.project_dir%/public/assets/images/prestations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        rendezvous:
            uri_prefix: /assets/images/rendezvous
            upload_destination: '%kernel.project_dir%/public/assets/images/rendezvous'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        category_prestation:
            uri_prefix: /assets/images/categoryprestations
            upload_destination: '%kernel.project_dir%/public/assets/images/categoryprestations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
