controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_available_slots:
    path: '/get-available-slots'
    controller: 'App\Controller\CalendarController::getAvailableSlots'

meta_image:
    path: '/assets/metatags.png'