# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.fedapay_private_key: '%env(FEDAPAY_PRIVATE_KEY)%'
    app.fedapay_public_key: '%env(FEDAPAY_PUBLIC_KEY)%'
    app.fedapay_env: '%env(FEDAPAY_ENV)%'

    feexpay.shop_id: '%env(FEEXPAY_SHOP_ID)%'
    feexpay.token: '%env(FEEXPAY_API_KEY)%'
    feexpay.callback_url: '%env(FEEXPAY_CALLBACK_URL)%'
    feexpay.error_callback_url: '%env(FEEXPAY_ERROR_CALLBACK_URL)%'
    feexpay.mode: '%env(FEEXPAY_MODE)%'

services:
    # Autoriser l'auto-câblage pour l'entité Rendezvous
    App\Entity\Rendezvous: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    FedaPay\FedaPay:
        arguments:

    FedaPay\Transaction:
        arguments:

    App\Service\FedapayService:
        arguments:
            $privateKey: '%app.fedapay_private_key%'
            $publicKey: '%app.fedapay_public_key%'
            $fedapayEnv: '%app.fedapay_env%'

    App\Service\FeexpayService:
        arguments:
            $token: '%feexpay.token%'
            $shopId: '%feexpay.shop_id%'
            $callbackUrl: '%feexpay.callback_url%'
            $errorCallbackUrl: '%feexpay.error_callback_url%'
            $mode: '%feexpay.mode%'